@startuml

class Deck {
  - java.util.ArrayList<Card> cards
  + createFullDeck(): void
  + shuffle(): void
  + dealCard(): Card
  + cardsLeft(): int
  + toString(): String
}

class Card {
  - String suit
  - String rank
  - int value
  + getSuit(): String
  + getRank(): String
  + getValue(): int
  + setValue(int): void
  + toString(): String
}

class Person {
  - java.util.ArrayList<Card> hand
  + getHand(): java.util.ArrayList<Card>
  + addCard(Card): void
  + getHandTotal(): int
  + clearHand(): void
  + isBusted(): boolean
  + getHand(boolean): String
}

class Player extends Person {
  - double money
  - double bet
  - boolean isStanding
  + getMoney(): double
  + setMoney(double): void
  + getBet(): double
  + setBet(double): void
  + isStanding(): boolean
  + stand(): void
  + resetStand(): void
}

class Dealer extends Person

class Jokes {
  {static} - java.util.ArrayList<String> jokes
  {static} + loadJokes(): void
  {static} + nextJoke(): String
}

@enduml